language: ruby

services:
  -postgresql

before_script:
  - psql -c "CREATE DATABASE bookmark_manager_test;" -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - psql -c "CREATE TABLE bookmarks (id SERIAL PRIMARY KEY, url VARCHAR(120), title VARCHAR(30));" -U postgres

script:
  - bundle exec rspec
